# Required Secrets:
# - NPM_TOKEN: NPM authentication token for publishing packages

name: Deploy to NPM

on:
  push:
    branches: [ main ]
    paths: [ 'package.json' ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
    
    - name: Build package
      run: npm run build
    
    - name: Publish to NPM
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    
    - name: Create Git Tag
      if: success()
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag -a "v$(node -p "require('./package.json').version")" -m "Release v$(node -p "require('./package.json').version")"
        git push origin "v$(node -p "require('./package.json').version")"
    
    - name: Create GitHub Release
      if: success()
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v$(node -p "require('./package.json').version")
        release_name: Release v$(node -p "require('./package.json').version")
        body: |
          ## Changes in v$(node -p "require('./package.json').version")
          
          - Automated release from package.json update
          - Package built and published to NPM
          
          ### Installation
          ```bash
          npm install ipds
          ```
        draft: false
        prerelease: false
